linux-octagon: Remove PKG:{PN} which rename to existing package
ERROR: linux-octagon-4.4.35-r1 do_package: package "kernel-base" is renamed to "kernel-base" using PKG:kernel-base, but package name already exists